#ifndef GLOBALDEFINE_H
#define GLOBALDEFINE_H
namespace Mh{
typedef enum{  
    OPENDEVICE,
    OPENMCKERNEL,
    SETAXISSOFTLIMIT,
    ENABLESOFTLIMIT,
    SETAXISPOSITONMODE,
    SETAXISVEL,
    SETAXISACC,
    SETAXISJERK,
    SETINTERPOLATIONVEL,
    SETINTERPOLATIONACC,
    SETINTERPOLATIONJERK,
    SETVELCOMMAND,
    GETDRIVERSTATE,
    GETAXISPOSITION,
    GETDRIVERPOS,
    CONTIOPENLIST,
    CONTISETLOOKHEADMODE,
    CONTILINEUNIT,
    CONTISTARTLIST,
    POSITIONDRIVE,
    SETAXISCOMMANDMODE,
    CONTISTOPLIST,
    CONTICLOSELIST,
    STOPALLAXIS,
    CLOSEDEVICE,
}MotionKernelType;
typedef enum{
    PTP,
    LIN,
}RobotPathPlaningType;
}
#endif