// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: DemConDataTransfer.proto
#ifndef GRPC_DemConDataTransfer_2eproto__INCLUDED
#define GRPC_DemConDataTransfer_2eproto__INCLUDED

#include "DemConDataTransfer.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace ExternalDataTransfer {

// 定义服务
class RPCDemConData final {
 public:
  static constexpr char const* service_full_name() {
    return "ExternalDataTransfer.RPCDemConData";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::ExternalDataTransfer::Pt_DataResult* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>> AsyncSetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>>(AsyncSetEnableStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>> PrepareAsyncSetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>>(PrepareAsyncSetEnableStateRaw(context, request, cq));
    }
    virtual ::grpc::Status GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>> AsyncGetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>>(AsyncGetAXISPOSSCARARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>> PrepareAsyncGetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>>(PrepareAsyncGetAXISPOSSCARARaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      virtual void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>* AsyncSetEnableStateRaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_DataResult>* PrepareAsyncSetEnableStateRaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* AsyncGetAXISPOSSCARARaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* PrepareAsyncGetAXISPOSSCARARaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::ExternalDataTransfer::Pt_DataResult* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>> AsyncSetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>>(AsyncSetEnableStateRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>> PrepareAsyncSetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>>(PrepareAsyncSetEnableStateRaw(context, request, cq));
    }
    ::grpc::Status GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>> AsyncGetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>>(AsyncGetAXISPOSSCARARaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>> PrepareAsyncGetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>>(PrepareAsyncGetAXISPOSSCARARaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetEnableState(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetAXISPOSSCARA(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>* AsyncSetEnableStateRaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_DataResult>* PrepareAsyncSetEnableStateRaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_EnableState& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* AsyncGetAXISPOSSCARARaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* PrepareAsyncGetAXISPOSSCARARaw(::grpc::ClientContext* context, const ::ExternalDataTransfer::Pt_DataVoid& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetEnableState_;
    const ::grpc::internal::RpcMethod rpcmethod_GetAXISPOSSCARA_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetEnableState(::grpc::ServerContext* context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response);
    virtual ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetEnableState() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetEnableState(::grpc::ServerContext* context, ::ExternalDataTransfer::Pt_EnableState* request, ::grpc::ServerAsyncResponseWriter< ::ExternalDataTransfer::Pt_DataResult>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetAXISPOSSCARA() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAXISPOSSCARA(::grpc::ServerContext* context, ::ExternalDataTransfer::Pt_DataVoid* request, ::grpc::ServerAsyncResponseWriter< ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetEnableState<WithAsyncMethod_GetAXISPOSSCARA<Service > > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SetEnableState() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ExternalDataTransfer::Pt_EnableState, ::ExternalDataTransfer::Pt_DataResult>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ExternalDataTransfer::Pt_EnableState* request, ::ExternalDataTransfer::Pt_DataResult* response) { return this->SetEnableState(context, request, response); }));}
    void SetMessageAllocatorFor_SetEnableState(
        ::grpc::experimental::MessageAllocator< ::ExternalDataTransfer::Pt_EnableState, ::ExternalDataTransfer::Pt_DataResult>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ExternalDataTransfer::Pt_EnableState, ::ExternalDataTransfer::Pt_DataResult>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetEnableState(
      ::grpc::CallbackServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetEnableState(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetAXISPOSSCARA() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ExternalDataTransfer::Pt_DataVoid, ::ExternalDataTransfer::Pt_AXISPOS_SCARA>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::ExternalDataTransfer::Pt_DataVoid* request, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* response) { return this->GetAXISPOSSCARA(context, request, response); }));}
    void SetMessageAllocatorFor_GetAXISPOSSCARA(
        ::grpc::experimental::MessageAllocator< ::ExternalDataTransfer::Pt_DataVoid, ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(1);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ExternalDataTransfer::Pt_DataVoid, ::ExternalDataTransfer::Pt_AXISPOS_SCARA>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetAXISPOSSCARA(
      ::grpc::CallbackServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetAXISPOSSCARA(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SetEnableState<ExperimentalWithCallbackMethod_GetAXISPOSSCARA<Service > > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SetEnableState<ExperimentalWithCallbackMethod_GetAXISPOSSCARA<Service > > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetEnableState() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetAXISPOSSCARA() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetEnableState() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetEnableState(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetAXISPOSSCARA() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetAXISPOSSCARA(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SetEnableState() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetEnableState(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetEnableState(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetEnableState(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetAXISPOSSCARA() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetAXISPOSSCARA(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetAXISPOSSCARA(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetAXISPOSSCARA(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetEnableState : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetEnableState() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ExternalDataTransfer::Pt_EnableState, ::ExternalDataTransfer::Pt_DataResult>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ExternalDataTransfer::Pt_EnableState, ::ExternalDataTransfer::Pt_DataResult>* streamer) {
                       return this->StreamedSetEnableState(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetEnableState() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetEnableState(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_EnableState* /*request*/, ::ExternalDataTransfer::Pt_DataResult* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetEnableState(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ExternalDataTransfer::Pt_EnableState,::ExternalDataTransfer::Pt_DataResult>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetAXISPOSSCARA : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetAXISPOSSCARA() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ExternalDataTransfer::Pt_DataVoid, ::ExternalDataTransfer::Pt_AXISPOS_SCARA>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ExternalDataTransfer::Pt_DataVoid, ::ExternalDataTransfer::Pt_AXISPOS_SCARA>* streamer) {
                       return this->StreamedGetAXISPOSSCARA(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetAXISPOSSCARA() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetAXISPOSSCARA(::grpc::ServerContext* /*context*/, const ::ExternalDataTransfer::Pt_DataVoid* /*request*/, ::ExternalDataTransfer::Pt_AXISPOS_SCARA* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetAXISPOSSCARA(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ExternalDataTransfer::Pt_DataVoid,::ExternalDataTransfer::Pt_AXISPOS_SCARA>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetEnableState<WithStreamedUnaryMethod_GetAXISPOSSCARA<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetEnableState<WithStreamedUnaryMethod_GetAXISPOSSCARA<Service > > StreamedService;
};

}  // namespace ExternalDataTransfer


#endif  // GRPC_DemConDataTransfer_2eproto__INCLUDED
